ALTER TABLE address ADD COLUMN city VARCHAR(80);
ALTER TABLE address ALTER COLUMN number TYPE VARCHAR(20);

ALTER TABLE pet ALTER COLUMN name TYPE VARCHAR(100);
ALTER TABLE pet ALTER COLUMN age TYPE DECIMAL(4,1) USING age::NUMERIC;
ALTER TABLE pet ALTER COLUMN weight TYPE DECIMAL(5,2) USING weight::NUMERIC;
ALTER TABLE pet ALTER COLUMN race TYPE VARCHAR(80);
